### ISSUE TITLE
Vanilla insallation erroring on useContext

### ISSUE THREAD

**Issue by ian** [clerkinc/clerk-expo-starter#5]
I have tried multiple versions of @clerk/clerk-expo:
- 0.11.3 FAIL
- 0.12.1 FAIL
- 0.12.2 FAIL

No matter what, Expo will always error with "null is not an object". 

![IMG_65FC8E24E37E-1](https://user-images.githubusercontent.com/19853/218321846-35670030-163f-47e7-8321-93a7d0f31313.jpeg)

Again, this is the default install of the repo, no changes were made. Here is App.tsx:

```ts
import React from "react";
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
import useCachedResources from "./hooks/useCachedResources";
import Navigation from "./navigation";
import { ClerkProvider } from "@clerk/clerk-expo";
import { tokenCache } from "./cache";

// Your publishable Key goes here
const publishableKey = "...";

// if you are using frontendAPI please update this with a value and update the ClerkProvider to frontendApi={frontendApi}
const frontendApi = "clerk.[your-domain].com";
export default function App() {
  const isLoadingComplete = useCachedResources();

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <ClerkProvider publishableKey={publishableKey} tokenCache={tokenCache}>
        <SafeAreaProvider>
          <Navigation />
          <StatusBar />
        </SafeAreaProvider>
      </ClerkProvider>
    );
  }
}

```

**Comment by ian** [comment]
I have verified this behavior across other applications, which is what brought me here. No installation of @clerk/clerk-expo works without the above error.

**Comment by SokratisVidros** [comment]
I had the same issue when I upgraded my local XCode tooling. Can you please clone the latest version of the repo from scratch and try again?

**Comment by SokratisVidros** [comment]
Which library? @clerk/expo?

**Comment by ian** [comment]
Yes - @clerk/clerk-expo does NOT work with 18.1

**Comment by SokratisVidros** [comment]
Currently it's pinned to [React 18.2](https://github.com/clerkinc/javascript/blob/main/packages/expo/package.json#L42). I can't tell for sure what was happening with a previous version of Expo in React.18.1.

**Comment by ian** [comment]
That's a dev-dependency. You need to set the specific version as a peerDependency:

```
"peerDependencies": {
    "react": ">=18.2"
 },
```

**Comment by SokratisVidros** [comment]
My bad, I've send the wrong link.

**Comment by nikosdouvlis** [comment]
Hello @ian , thanks for the report. We've just deployed many Expo-related improvements, including changes in our build process that should help with your issue.

Could you please try installing the latest by running `npm i @clerk/clerk-expo@latest`? Feel free to ping us again if you hit any other issue.

**Comment by nikosdouvlis** [comment]
This is fixed in the latest versions
